package com.tepav.reader.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table FILE.
 */
public class File implements Serializable {

    private Long id;
    private String file_id;
    private String name;
    private String url;
    private String path;

    public File() {
    }

    public File(Long id) {
        this.id = id;
    }

    public File(Long id, String file_id, String name, String url, String path) {
        this.id = id;
        this.file_id = file_id;
        this.name = name;
        this.url = url;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFile_id() {
        return file_id;
    }

    public void setFile_id(String file_id) {
        this.file_id = file_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
