package com.tepav.reader.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table GUNLUK.
 */
public class Gunluk implements Serializable {

    private Long id;
    private String gunluk_id;
    private String btitle;
    private String bcontent;
    private String bdate;
    private String pfullname;
    private String ptype;
    private String ptitle;
    private Integer persistanceType;
    private String pimage;

    public Gunluk() {
    }

    public Gunluk(Long id) {
        this.id = id;
    }

    public Gunluk(Long id, String gunluk_id, String btitle, String bcontent, String bdate, String pfullname, String ptype, String ptitle, Integer persistanceType, String pimage) {
        this.id = id;
        this.gunluk_id = gunluk_id;
        this.btitle = btitle;
        this.bcontent = bcontent;
        this.bdate = bdate;
        this.pfullname = pfullname;
        this.ptype = ptype;
        this.ptitle = ptitle;
        this.persistanceType = persistanceType;
        this.pimage = pimage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGunluk_id() {
        return gunluk_id;
    }

    public void setGunluk_id(String gunluk_id) {
        this.gunluk_id = gunluk_id;
    }

    public String getBtitle() {
        return btitle;
    }

    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }

    public String getBcontent() {
        return bcontent;
    }

    public void setBcontent(String bcontent) {
        this.bcontent = bcontent;
    }

    public String getBdate() {
        return bdate;
    }

    public void setBdate(String bdate) {
        this.bdate = bdate;
    }

    public String getPfullname() {
        return pfullname;
    }

    public void setPfullname(String pfullname) {
        this.pfullname = pfullname;
    }

    public String getPtype() {
        return ptype;
    }

    public void setPtype(String ptype) {
        this.ptype = ptype;
    }

    public String getPtitle() {
        return ptitle;
    }

    public void setPtitle(String ptitle) {
        this.ptitle = ptitle;
    }

    public Integer getPersistanceType() {
        return persistanceType;
    }

    public void setPersistanceType(Integer persistanceType) {
        this.persistanceType = persistanceType;
    }

    public String getPimage() {
        return pimage;
    }

    public void setPimage(String pimage) {
        this.pimage = pimage;
    }

}
